services:
  otel-lgtm:
    # https://github.com/grafana/docker-otel-lgtm/releases
    image: grafana/otel-lgtm:0.11.5
    container_name: otel-lgtm
    ports:
      - 3000:3000
      - 4317:4317
      - 4318:4318
    # volumes:
    #   - ${PWD}/Docker/prometheus.yml:/otel-lgtm/prometheus.yaml
    #   - ${PWD}/Docker/grafana/provisioning:/otel-lgtm/grafana/conf/provisioning
    networks:
      otel:
    # profiles:
    #   - all
    #   - otel-all
    #   - otel-no-monitoring

networks:
  otel: