services:
  otel-lgtm:
    # https://github.com/grafana/docker-otel-lgtm/releases
    image: grafana/otel-lgtm:0.11.5
    container_name: otel-lgtm
    ports:
      - 3000:3000 # grafana
      - 4317:4317 # otel grpc
      - 4318:4318 # otel http
      - 3200:3200 # tempo
      - 3100:3100 # loki
    networks:
      otel:

networks:
  otel: