services:
  otel-lgtm:
    # https://github.com/grafana/docker-otel-lgtm/releases
    image: grafana/otel-lgtm:0.11.6
    container_name: otel-lgtm
    ports:
      - 3000:3000 # grafana
      - 4317:4317 # otel grpc
      - 4318:4318 # otel http
      - 3200:3200 # tempo
      - 3100:3100 # loki
    networks:
      otel:
    environment:
      - GF_PATHS_PROVISIONING=/opt/grafana-provisioning
    volumes:
      - ./grafana-provisioning:/opt/grafana-provisioning
  # Due to lacking "Access-Control-Allow-Origin"-header from tempo API we'll spin up an nginx as proxy to add this
  # Not overkill at all.
  tempo-proxy:
    image: nginx
    container_name: tempo-proxy
    ports:
      - 3299:80
    networks:
      otel:
    volumes:
      - ./tempo-proxy-nginx.conf:/etc/nginx/nginx.conf

networks:
  otel: